### ISSUE TITLE
CSS compile error on next.js

### ISSUE THREAD

**Issue by nipunasudha** [coderixxinfotech/bitcoin-wallet-adapter#2]
⨯ /Users/nipuna/paragon/bitcoin-projects/dx-runes/node_modules/bitcoin-wallet-adapter/dist/styles.css:8
*,
^

SyntaxError: Unexpected token '*'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at mod.require (/Users/nipuna/paragon/bitcoin-projects/dx-runes/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/nipuna/paragon/bitcoin-projects/dx-runes/node_modules/bitcoin-wallet-adapter/dist/index.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  page: '/lab2'
}

**Comment by pRay01** [comment]
are you using nextjs or reactjs?
